server:
    port: 3000

spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: ccdccd
        url: jdbc:mysql://localhost:3306/securitydb?createDatabaseIfNotExist=true
        username: root
    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: true
        properties:
            hibernate:
                format_sql: true
                dialect: org.hibernate.dialect.MySQLDialect
